### ISSUE TITLE
Not an issue: Will this help me?

### ISSUE THREAD

**Issue by ghyujkilop** [radj307/caco-alch-registry-builder#2]
Hey man, thanks for making this! I'm not sure about one thing, would this patcher help my load order and how exactly would it help? I'm just confused as to what it would do is all.

https://modwat.ch/u/mattski123

**Comment by radj307** [comment]
Ah, my apologies, this isn't actually a Synthesis patcher; although it does use Mutagen.  
This is a generator program for one of my other projects, [alch](https://github.com/radj307/alch).  

I've added a `SynthesisMeta.json` file so that it is excluded from the search results in Synthesis.  
Thanks for the report!
